---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Stale

on:
  schedule:
    - cron: "0 8 * * *" # Every day at 08:00
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read # required to read repository content
  packages: read # required to read packages metadata
  statuses: read # required to read commit statuses

jobs:
  stale:
    name: 🧹 Clean up stale issues and PRs
    runs-on: ubuntu-latest

    permissions:
      contents: write # required for the delete-branch option
      issues: write # required to close and comment on stale issues
      pull-requests: write # required to close and comment on stale PRs
    steps:
      - uses: ivuorinen/actions/stale@8395dad6b7d5d7d2e1d016cac1eede33ab404a3c # v2026.06.18
